config/routes.rb
Kuchbhi::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to:"static_pages#home"
  devise_for :users

  resources :service_areas
  resources :vendors
  resources :shopping_cart do 
    
  end
  post 'add_to_shopping_cart', to: "shopping_carts#add_to_cart"

  match '/search', to: 'vendors#index', via: 'get'

end

app/models/admin_user.rb
# == Schema Information
#
# Table name: admin_users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#

class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  vendor_id  :integer
#  created_at :datetime
#  updated_at :datetime
#

class Category < ActiveRecord::Base
	has_many :meals
	belongs_to :vendor


end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text
#  menu_id     :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Item < ActiveRecord::Base
	has_and_belongs_to_many :meals
end

app/models/items_meals.rb
# == Schema Information
#
# Table name: items_meals
#
#  meal_id    :integer
#  item_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class ItemsMeals < ActiveRecord::Base
end

app/models/meal.rb
# == Schema Information
#
# Table name: meals
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  category_id :integer
#  vendor_id   :integer
#  nonvegtag   :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

class Meal < ActiveRecord::Base
	acts_as_taggable_on :cuisines
	belongs_to :vendor
	belongs_to :category
	has_and_belongs_to_many :time_plans
	has_and_belongs_to_many :items
	has_many :orders
	has_many :prices
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id           :integer          not null, primary key
#  from         :date
#  to           :date
#  user_id      :integer
#  meal_id      :integer
#  time_plan_id :integer
#  uaddress_id  :integer
#  price_id     :integer
#  created_at   :datetime
#  updated_at   :datetime
#

class Order < ActiveRecord::Base
	belongs_to :user
	belongs_to :meal
	belongs_to :uaddress
	belongs_to :price
end

app/models/price.rb
# == Schema Information
#
# Table name: prices
#
#  id           :integer          not null, primary key
#  mrp          :integer
#  meal_id      :integer
#  time_plan_id :integer
#  created_at   :datetime
#  updated_at   :datetime
#

class Price < ActiveRecord::Base
	belongs_to :meal
	belongs_to :time_plan
	has_many :orders

end

app/models/review.rb
# == Schema Information
#
# Table name: reviews
#
#  id         :integer          not null, primary key
#  comment    :text
#  vendor_id  :integer
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Review < ActiveRecord::Base
	belongs_to :vendor
	belongs_to :user
end

app/models/service_area.rb
# == Schema Information
#
# Table name: service_areas
#
#  id         :integer          not null, primary key
#  location   :string(255)
#  pincode    :integer
#  city       :string(255)
#  vendor_id  :integer
#  created_at :datetime
#  updated_at :datetime
#

class ServiceArea < ActiveRecord::Base
	has_many :vendor_areas
	has_many :vendors, through: :vendor_areas
	accepts_nested_attributes_for :vendor_areas, :allow_destroy => true
	validates :vendor_id, presence: true

	def name
    return self.location
	end
	
	def self.search(searchcity, searchloc, searchpincode )
		if searchcity
			if searchloc
				if searchpincode
					find(:all, :conditions => ['city LIKE ? AND location LIKE ? AND pincode LIKE ?', "%#{searchcity}%", "%#{searchloc}%","%#{searchpincode}%"])
				else
					find(:all, :conditions => ['city LIKE ? AND location LIKE ?', "%#{searchcity}%", "%#{searchloc}%"])
				end
			else
				if searchpincode
					find(:all, :conditions => ['city LIKE ? AND pincode LIKE ?', "%#{searchcity}%","%#{searchpincode}%"])
				else
					find(:all, :conditions => ['city LIKE ?', "%#{searchcity}%"])
				end
			end
		else
			if searchloc
				if searchpincode
					find(:all, :conditions => ['location LIKE ? AND pincode LIKE ?', "%#{searchloc}%","%#{searchpincode}%"])
				else
					find(:all, :conditions => ['location LIKE ?', "%#{searchloc}%"])
				end
			else
				if searchpincode
					find(:all, :conditions => ['pincode LIKE ?', "%#{searchpincode}%"])
				else
					find(:all)
				end
			end
		end
	end

end

app/models/shopping_cart.rb
# == Schema Information
#
# Table name: shopping_carts
#
#  id         :integer          not null, primary key
#  created_at :datetime
#  updated_at :datetime
#

class ShoppingCart < ActiveRecord::Base
	acts_as_shopping_cart
end

app/models/time_plan.rb
# == Schema Information
#
# Table name: time_plans
#
#  id         :integer          not null, primary key
#  days       :integer
#  plan_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class TimePlan < ActiveRecord::Base
	has_and_belongs_to_many :meals
	has_many :prices
end

app/models/uaddress.rb
# == Schema Information
#
# Table name: uaddresses
#
#  id             :integer          not null, primary key
#  user_id        :integer
#  company_name   :string(255)
#  flat_no        :string(255)
#  street_address :string(255)
#  location       :string(255)
#  city           :string(255)
#  landmark       :string(255)
#  created_at     :datetime
#  updated_at     :datetime
#

class Uaddress < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  name                   :string(255)
#  email                  :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#

class User < ActiveRecord::Base

  has_many :orders
  has_many :uaddresses


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vaddress.rb
# == Schema Information
#
# Table name: vaddresses
#
#  id             :integer          not null, primary key
#  vendor_id      :integer
#  bldg_no        :string(255)
#  street_address :string(255)
#  location       :string(255)
#  city           :string(255)
#  landmark       :string(255)
#  created_at     :datetime
#  updated_at     :datetime
#

class Vaddress < ActiveRecord::Base
	belongs_to :vendor
end

app/models/vendor.rb
# == Schema Information
#
# Table name: vendors
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Vendor < ActiveRecord::Base
	has_many :categories
	has_many :vendor_areas
	has_many :service_areas, through: :vendor_areas
	has_many :meals
	has_many :orders
	has_one  :vaddress
	accepts_nested_attributes_for :vendor_areas, :allow_destroy => true
end

app/models/vendor_area.rb
# == Schema Information
#
# Table name: vendor_areas
#
#  id              :integer          not null, primary key
#  vendor_id       :integer
#  service_area_id :integer
#  created_at      :datetime
#  updated_at      :datetime
#

class VendorArea < ActiveRecord::Base
	belongs_to :vendor
	belongs_to :service_area
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/layouts/_footer.html.haml
/ === Footer ===
.footer
  .container
    .row
      .col-md-4.md-margin-bottom-40
        / About
        .headline
          %h2 About
        %p.margin-bottom-25.md-margin-bottom-40 
          Edunable is a platform to provide internships with leading organizations in different field of studies.
      / /col-md-4
      .col-md-4.md-margin-bottom-40
      
      / /col-md-4
      .col-md-4
        / Monthly Newsletter
        .headline
          %h2 Contact Us
        %address.md-margin-bottom-40
          25, Lorem Lis Street, Orange
          %br/
          California, US
          %br/
          Phone: 800 123 3456
          %br/
          Fax: 800 123 3456
          %br/
          Email:
          %a{href: "mailto:info@anybiz.com"} info@anybiz.com
      / /col-md-4
    / /row
  / /container
/ /footer
/ === End Footer ===
/ === Copyright ===
.copyright
  .container
    .row
      .col-md-6
        %p.copyright-space
          2013 © Edunable. ALL Rights Reserved.
          %a{href: "#"} Privacy Policy
          |
          %a{href: "#"} Terms of Service
      .col-md-6
        %a{href: "index.html"}
          %img#logo-footer.pull-right{alt: "", src: "assets/img/logo2-default.png"}/
    / /row
  / /container
/ /copyright
/ === End Copyright ===
/ JS Global Compulsory

app/views/layouts/_header.html.haml
.top
  .container
    %ul.loginbar.pull-right
      %li.devider
      %li
        %a{href: "page_faq.html"} FAQ
      %li.devider
      %li
        - if user_signed_in?
          =link_to 'Sign out', destroy_user_session_path, method: :delete
        -else
          =link_to('Login', new_user_session_path)
/ /top
/ === End Top ===
/ === Header ===
.header
  .navbar.navbar-default{role: "navigation"}
    .container
      / Brand and toggle get grouped for better mobile display
      .navbar-header
        %button.navbar-toggle{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", type: "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{href: root_path}
          =image_tag('logo1-default.png')
      / Collect the nav links, forms, and other content for toggling
      .collapse.navbar-collapse.navbar-responsive-collapse
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            %a.dropdown-toggle{"data-close-others" => "false", "data-delay" => "0", "data-hover" => "dropdown",  href: root_path}
              Home
          %li.dropdown
            %a.dropdown-toggle{"data-close-others" => "false", "data-delay" => "0", "data-hover" => "dropdown", href: "#"}
              Opportunities
          
          %li.dropdown
            -if user_signed_in?
              %a.dropdown-toggle{"data-close-others" => "false", "data-delay" => "0", "data-hover" => "dropdown", href:"#"}
                Profile
            -else
              %a.dropdown-toggle{"data-close-others" => "false", "data-delay" => "0", "data-hover" => "dropdown", href: "#"}
                Register
  
          / /input-group
      / /navbar-collapse
/ /header

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kuchbhi</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class='container'>
		<%= yield %>
	</div>
	<%= render 'layouts/footer' %>
</body>
</html>

app/views/partials/_search_form.html.haml
.row.text-center
	.col-md-10.col-md-offset-1
		.panel.panel-red.margin-bottom-40
			.panel-body
				= form_tag vendors_path, :method => 'get', class: 'form-inline' do
					.form-group
						= label_tag :searchcity, "City:"
					.form-group
						= text_field_tag :searchcity, params[:searchcity], class: 'form-control'
					.form-group
						= label_tag :searchloc, "Location:"
					.form-group
						= text_field_tag :searchloc, params[:searchloc], class: 'form-control'
					.form-group
						=label_tag 'or,' 
					.form-group
						=label_tag :searchpincode, "Pincode:" 
					.form-group
						=text_field_tag :searchpincode, params[:searchpincode], class: 'form-control'
					.form-group
						=submit_tag "Search", :name => nil, class: 'btn-u btn-u-red'