config/routes.rb
Kuchbhi::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to:"static_pages#home"
  devise_for :users

  resources :service_areas
  resources :vendors
  resources :shopping_cart do 
    
  end
  post 'add_to_shopping_cart', to: "shopping_carts#add_to_cart"

  match '/search', to: 'vendors#index', via: 'get'

end

app/models/vendor.rb
# == Schema Information
#
# Table name: vendors
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Vendor < ActiveRecord::Base
	has_many :categories
	has_many :vendor_areas
	has_many :service_areas, through: :vendor_areas
	has_many :meals
	has_many :orders
	has_one  :vaddress
	accepts_nested_attributes_for :vendor_areas, :allow_destroy => true
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
	
	def index
	    
	    @q = Vendor.search(params[:q])
		per_page = 2
	    
	    if params[:q]
			@vendors_arr = @q.result(distinct: true)    
	    else 
		    
			@ss = ServiceArea.search(params[:searchcity], params[:searchloc], params[:searchpincode])
			@vendors_arr = Array.new
			@ss.each do |s|
				s.vendors.each do |v|				
					@vendors_arr<<v
				end
			end
	    end
	    @vendors = Kaminari.paginate_array(@vendors_arr).page(params[:page]).per(per_page)
	end

	def show
		@vendor = Vendor.find(params[:id])
		@address = @vendor.vaddress

		@categories = @vendor.categories

		@shopping_cart = get_current_cart

	end

private
  def vendor_params
    params.require(:vendor).permit(:name, vendor_area:[:vendor_id, :service_area_id])
  end

  def get_current_cart
  	if session[:shopping_cart_id]
  		shopping_cart_id = session[:shopping_cart_id]
  		ShoppingCart.find(shopping_cart_id)
  	end
  end

end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vendors/_shopping_cart_item.html.haml
.row
	.col-md-12
		=shopping_cart_item.item.name
		=shopping_cart_item.quantity
		=shopping_cart_item.price

app/views/vendors/index.html.haml
.clearfix.margin-bottom-40
.row
  .col-md-12.text-center
    %h2 Vendors serving in your area
.row
  .col-md-3
    .panel.panel-grey
      .panel-body
        = search_form_for @q do |f|
          = f.label :name_cont
          = f.text_field :name_cont
          = f.label "Veg"
          = check_box_tag "q[meal_nonveg_eq][]", "veg"
          = f.label "Non-Veg"
          = check_box_tag "q[meal_nonveg_eq][]", "nonveg"          
          = f.submit "search"
  .col-md-9
    -@vendors.each do |vendor|
      -address = vendor.vaddress
      .panel.panel-red
        .panel-heading
          .panel-title
            %strong 
              = link_to vendor.name, vendor, class: 'white_font'
            .pull-right
              Star Rating and reviews
          -if !address.nil?
            =address.bldg_no
            ,
            =address.street_address.humanize
            ,
            %strong
              =address.location.humanize
              ,
            =address.city.humanize
        .panel-body
          .row
            .col-md-2
              Menu and other details
            .col-md-10
              .pull-right
                =button_to 'Got to the Menu', vendor, class: 'btn btn-default', method: 'get'

    =paginate @vendors, theme: 'twitter-bootstrap-3'

app/views/vendors/show.html.haml
.clearfix.margin-bottom-40
.row
	.col-md-10
		.panel.panel-red
			.panel-heading
				.pull-left
					=image_tag "http://upload.wikimedia.org/wikipedia/en/4/4a/Faaso%27s_logo.JPG", height:50,width:100
				%h4.white_font
					%strong
						=@vendor.name
				.pull-right
					Star Ratings
				%p.white_font
					-if !@address.nil?
						
						=@address.bldg_no
						,
						=@address.street_address.humanize
						,
						=@address.location.humanize
						,
						=@address.city.humanize

			.panel-body
				.row
					.col-md-12
						Some details
				.clearfix.margin-bottom-40
				.row.tab-v1
					%ul.nav.nav-tabs
						%li.active
							=link_to "Menu", '#menu', "data-toggle" => 'tab'
						%li
							=link_to "Reviews", '#reviews', "data-toggle" => 'tab'
						%li
							=link_to "Info", '#info', "data-toggle" => 'tab'
					.tab-content
						#menu.tab-pane.active
							.row.tab-v3
								.col-md-3
									%ul.nav.nav-pills.nav-stacked
										-@categories.each_with_index do |c,i|
											%li{style: 'list-style-type:none;', class: "#{'active' if i ==0}"}
												=link_to c.name, "##{c.id}", "data-toggle" => 'tab'	
								.col-md-9
									.tab-content.meal-box
										-@categories.each_with_index do |c,i|
											-meals = c.meals
											.tab-pane{id: c.id,class: "#{'active' if i ==0}"}
												-meals.each do |m|
													.meal-cont
														-items = m.items
														.row
															.col-md-9
																%p
																	%strong	
																		= m.name			
																	%br	
																	-items.each do |item|
																		=item.name
																		,
															.col-md-3.pull-right
																=select_tag :quantity, options_for_select(1..10)
																=link_to(fa_icon("plus-circle", text:"Add to cart", class: 'green'), add_to_shopping_cart_path(meal_id: m.id, vendor_id: @vendor.id), method:'post')
																
												
						#reviews.tab-pane
							Reviews
						#info.tab-pane
							Info
	.col-md-2
		Shopping cart
		
		-if @shopping_cart
			
			=render partial: 'shopping_cart_item', collection: @shopping_cart.shopping_cart_items
			=button_to 'Checkout', '#', class: 'btn btn-success'
		-else						
			Add items from menu